routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@welcome')->name('index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/view-barang/{id}', 'HomeController@view_barang')->name('viewbarang');
Route::get('/input-tag/{id}', 'TagBarangController@input_tag');
Route::delete('/hapus-tag/{id}/{id2}', 'TagBarangController@delete_tag');
Route::get('/user-profile/update-profile', 'UserProfileController@update_profile');
Route::put('/user-profile/update-profile', 'UserProfileController@process_profile');

Route::resource('barang', 'BarangController');
Route::resource('kategori', 'KategoriController');
Route::resource('tag', 'TagController');
Route::resource('user-profile', 'UserProfileController');
Route::resource('tag-barang', 'TagBarangController');

app/Barang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    protected $table = 'barang';
    protected $fillable = ['gambar', 'deskripsi', 'tanggal_menemukan', 'tempat_menemukan'];

    public function kategori()
    {
        return $this->hasOne('App\Kategori', 'id', 'id_kategori');
    }

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Barang;
use App\Kategori;
use Illuminate\Http\Request;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $barang = Barang::all();
        return view(('barang.index'), compact('barang'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dataBaru = true;
        $dataKategori = Kategori::all();
        return view('barang.form', compact('dataBaru', 'dataKategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'gambar' => 'required',
            'deskripsi' => 'required',
            'id_kategori' => 'required',
            'user_id' => 'required',
            'tanggal_menemukan' => 'required',
            'tempat_menemukan' => 'required',
        ]);

        $file = $request->file('gambar');
        $p = new Barang();

        $p->judul = $request->judul;
        $p->gambar = $file->getClientOriginalName();
        $p->deskripsi = $request->deskripsi;
        $p->id_kategori = $request->id_kategori;
        $p->tanggal_menemukan = $request->tanggal_menemukan;
        $p->tempat_menemukan = $request->tempat_menemukan;
        $p->user_id = $request->user_id;

        // isi dengan nama folder tempat kemana file diupload
        $tujuan_upload = 'data_file';
        $file->move($tujuan_upload, $file->getClientOriginalName());

        $p->save();
        return redirect()->route('barang.index')->with('status', 'Berhasil menambahkan barang!');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function show(Barang $barang)
    {
        return view('barang.view', compact('barang'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function edit(Barang $barang)
    {
        $dataBaru = false;
        $dataKategori = Kategori::all();
        return view('barang.form', compact('dataBaru', 'dataKategori', 'barang'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Barang $barang)
    {
        $this->validate($request, [
            'deskripsi' => 'required',
            'id_kategori' => 'required',
            'user_id' => 'required',
            'tanggal_menemukan' => 'required',
            'tempat_menemukan' => 'required',
        ]);

        $barang->judul = $request->judul;
        $file = $request->file('gambar');
        // dd($file);
        if ($file != null && $file->getSize() > 0) {
            $barang->gambar = $file->getClientOriginalName();
            $tujuan_upload = 'data_file';
            $file->move($tujuan_upload, $file->getClientOriginalName());
        }
        $barang->deskripsi = $request->deskripsi;
        $barang->id_kategori = $request->id_kategori;
        $barang->tanggal_menemukan = $request->tanggal_menemukan;
        $barang->tempat_menemukan = $request->tempat_menemukan;
        $barang->user_id = $request->user_id;

        $barang->save();

        return redirect()->route('barang.index')->with('status', 'Berhasil update barang!');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function destroy(Barang $barang)
    {
        $barang->delete();
        return redirect()->route('barang.index')->with('status', 'Berhasil menghapus barang!');;
    }
}

resources/views/barang/form.blade.php
@extends('layouts.app')

@section('content')

<main id="main">
    <br>
    <section id="featured-services" class="featured-services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6">
                    <!-- MULAI -->
                    <br>
                    <br>
                    <br>


                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <h3 class="mt-3">Daftar Barang Temuan</h3>
                                @include('share.showerrors')
                                @if (!$dataBaru)
                                <form action="{{ route('barang.update', $barang->id)}}" method="post"
                                    enctype="multipart/form-data">
                                    @else
                                    <form action="{{ route('barang.store') }}" method="post"
                                        enctype="multipart/form-data">
                                        @endif

                                        @csrf
                                        @if (!$dataBaru)
                                        @method('PUT')
                                        @endif


                                        {{-- user_id --}}
                                        <input type="hidden" class="form-control" name="user_id" id="user_id"
                                            value="{{ Auth::id() }}">

                                        Judul : <br>
                                        <input type="text" class="form-control" name="judul" id="judul"
                                            value="{{ $barang->judul?? ''}}">

                                        Gambar : <br>
                                        <input type="file" class="form-control" name="gambar" id="gambar">

                                        Deskripsi : <br>
                                        <textarea class="form-control" name="deskripsi"
                                            id="deskripsi">{{ $barang->deskripsi ?? ''}}</textarea>

                                        Tanggal Menemukan : <br>
                                        <input type="text" class="form-control" name="tanggal_menemukan"
                                            id="tanggal_menemukan" data-date-end-date="0d" value="{{ $barang->tanggal_menemukan?? ''}}">

                                        Tempat Menemukan : <br>
                                        <input type="text" class="form-control" name="tempat_menemukan"
                                            id="tempat_menemukan" value="{{ $barang->tempat_menemukan?? ''}}">

                                        Kategori : <br>
                                        <select class="form-control" name="id_kategori" id="id_kategori">
                                            @foreach ($dataKategori as $kategori)
                                            <option value="{{ $kategori->id }}">{{ $kategori->nama }}</option>
                                            @endforeach
                                        </select>

                                        <br>
                                        <input type="submit" value="Simpan" class="btn btn-sm btn-success">
                                        <a href="{{ route('barang.index') }}" class="btn btn-success btn-sm">Kembali</a>
                                    </form>

                            </div>
                        </div>
                    </div>


                    <!-- SELESAI -->
                </div>
            </div>
        </div>
    </section>
</main>
@endsection

@push('scriptcss')
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<link href="{{asset('enno/assets/vendor/datepicker/css/bootstrap-datepicker.standalone.min.css')}}" rel="stylesheet">
@endpush

@push('scriptjs')
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="{{asset('enno/assets/vendor/datepicker/js/bootstrap-datepicker.min.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#deskripsi').summernote();
        $('#tanggal_menemukan').datepicker({
            format: 'yyyy-mm-dd',
            todayBtn:true,
            todayHighlight:true
        });
    });
</script>
@endpush

resources/views/barang/index.blade.php
@extends('layouts.app')

@section('content')
<main id="main">
    <br>
    <section id="featured-services" class="featured-services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6">
                    <!-- MULAI -->
                    <br>
                    <br>
                    <br>


                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <h3 class="mt-3">Daftar Barang Temuan</h3>
                                <a class="btn btn-primary" href="/barang/create">Masukkan Barang Temuan Anda</a>
                                @include('share.message')
                                <br>
                                <br>
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">No</th>
                                            <th scope="col">Foto</th>
                                            <th scope="col">Deskripsi</th>
                                            <th scope="col">Kategori</th>
                                            <th scope="col">Tags</th>
                                            <th scope="col">Tanggal Ditemukan</th>
                                            <th scope="col">Tempat Ditemukan</th>
                                            <th scope="col">User</th>
                                            <th scope="col">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($barang ?? '' as $benda)
                                        <tr>
                                            <th scope="row">{{ $loop->iteration}}</th>
                                            <td><img src="{{asset('data_file/'.$benda->gambar)}}" class="img-fluid" alt="{{$benda->judul}}"></td>
                                            <td>{!! $benda->deskripsi !!}</td>
                                            <td>{{$benda->kategori->nama}}</td>
                                            <td>
                                                <ul>
                                                    @foreach ($benda->tags as $tag)
                                                    <li>{{ $tag->nama }}</li>
                                                    @endforeach    
                                                </ul>
                                            </td>
                                            <td>{{ date('d-m-Y', strtotime($benda->tanggal_menemukan))}}</td>
                                            <td>{{$benda->tempat_menemukan}}</td>
                                            <td>{{$benda->user->name}}</td>
                                            <td>
                                                <form action="{{route('barang.destroy', $benda->id)}}" method="post">
                                                    @method('delete')
                                                    @csrf
                                                    <a href="{{route('barang.show', $benda->id)}}"
                                                        class="badge badge-success">lihat</a>

                                                    <a href="{{route('barang.edit', $benda->id)}}"
                                                        class="badge badge-warning">edit</a>

                                                    <button type="submit" class="badge badge-danger"
                                                        class="d-inline">hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                    <!-- SELESAI -->
                </div>
            </div>
        </div>
    </section>
</main>
@endsection

@push('scriptjs')
<script src="{{ asset('enno/assets/vendor/swal.min.js') }}"></script>
@if ($message = Session::get('status'))
    <script>
    Swal.fire(
        'Data Barang',
        '{{ $message }}',
        'success'
    )
    </script>
@endif
@endpush

resources/views/barang/view.blade.php
@extends('layouts.app')

@section('content')
<main id="main">
    <br>
    <section id="featured-services" class="featured-services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6">
                    <!-- MULAI -->
                    <br>
                    <br>
                    <br>
                    <br>


                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <form action="{{route('barang.destroy', $barang->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                    <a class="btn btn-sm btn-primary" href="/barang">Daftar Barang</a>
                                    <a href="{{route('barang.edit', $barang->id)}}"
                                        class="btn btn-sm btn-warning">edit</a>

                                    <button type="submit" class="btn btn-sm btn-danger d-inline">hapus</button>
                                </form>

                                <h3>{{ $barang->judul }}</h3>
                                <img src="{{asset('data_file/'.$barang->gambar)}}" class="img-fluid" alt="{{$barang->judul}}"> <br>
                                Deskripsi : <br>
                                {!! $barang->deskripsi !!} <br>
                                
                                Kategori : {{$barang->kategori->nama}} <br>
                                Tanggal Menemukan : {{date('d-m-Y', strtotime($barang->tanggal_menemukan))}} <br>
                                Tempat Menemukan : {{$barang->tempat_menemukan}} <br>
                                Pengguna : {{$barang->user->name}} <br>
                                Tag/Label : 
                                <a href="/input-tag/{{$barang->id}}" class="btn btn-success btn-sm">Tambahkan Label</a>
                                <ul>
                                    @foreach ($barang->tags as $tag)
                                    <li>
                                        <form action="/hapus-tag/{{$barang->id}}/{{$tag->id}}" method="post">
                                            @method('delete')
                                            @csrf
                                            <button type="submit" class="badge badge-danger"
                                            class="badge badge-danger" title="klik untuk hapus">{{ $tag->nama }}</button>
                                        </form>
                                    </li>
                                    @endforeach    
                                </ul>
                            </div>
                        </div>
                    </div>


                    <!-- SELESAI -->
                </div>
            </div>
        </div>
    </section>
</main>
@endsection