routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@welcome')->name('index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/view-barang/{id}', 'HomeController@view_barang')->name('viewbarang');
Route::get('/input-tag/{id}', 'TagBarangController@input_tag');
Route::delete('/hapus-tag/{id}/{id2}', 'TagBarangController@delete_tag');
Route::get('/user-profile/update-profile', 'UserProfileController@update_profile');
Route::put('/user-profile/update-profile', 'UserProfileController@process_profile');

Route::resource('barang', 'BarangController');
Route::resource('kategori', 'KategoriController');
Route::resource('tag', 'TagController');
Route::resource('user-profile', 'UserProfileController');
Route::resource('tag-barang', 'TagBarangController');

app/Http/Controllers/TagBarangController.php
<?php

namespace App\Http\Controllers;

use App\Barang;
use App\TagBarang;
use App\Tag;
use Illuminate\Http\Request;

class TagBarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Barang $barang)
    {
        $tags = Tag::all();
        return view('tag_barang.form', compact('barang', 'tags'));
    }

    public function input_tag($id)
    {
        $barang = Barang::find($id);
        $tags = Tag::all();
        return view('tag_barang.form', compact('barang', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'id_barang' => 'required',
            'id_tag' => 'required',
        ]);

        $p = Barang::find($request->id_barang);
        $p->tags()->attach($request->id_tag);

        return redirect()->route('barang.show', $request->id_barang);
    }

    public function delete_tag($id, $id2)
    {
        $tagBarang = Barang::find($id);
        $tagBarang->tags()->detach($id2);
        return redirect()->route('barang.show', $id);
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\TagBarang  $tagBarang
     * @return \Illuminate\Http\Response
     */
    public function show(TagBarang $tagBarang)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TagBarang  $tagBarang
     * @return \Illuminate\Http\Response
     */
    public function edit(TagBarang $tagBarang)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TagBarang  $tagBarang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TagBarang $tagBarang)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TagBarang  $tagBarang
     * @return \Illuminate\Http\Response
     */
    public function destroy(TagBarang $tagBarang)
    {
        //
    }
}

resources/views/tag_barang/form.blade.php
@extends('layouts.app')

@section('content')

<main id="main">
    <br>
    <section id="featured-services" class="featured-services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6">
                    <!-- MULAI -->
                    <br>
                    <br>
                    <br>


                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <h3 class="mt-3">Tambah Tag</h3>
                                @include('share.showerrors')

                                <form action="{{ route('tag-barang.store')}}" method="post">
                                        @csrf

                                        Nama Barang : {{$barang->judul}} <br>
                                        <input type="hidden" name="id_barang" id="id_barang" value="{{ $barang->id }}">
                                        Tag : <br>
                                        <select name="id_tag" id="id_tag" class="form-control">
                                            @foreach ($tags as $tag)
                                            <option value="{{$tag->id}}">{{$tag->nama}}</option>
                                            @endforeach    
                                        </select>                                       

                                        
                                        <br>
                                        <input type="submit" value="Tambah" class="btn btn-sm btn-success">
                                        <a href="{{ route('barang.show', $barang->id) }}" class="btn btn-success btn-sm">Kembali</a>
                                    </form>

                            </div>
                        </div>
                    </div>


                    <!-- SELESAI -->
                </div>
            </div>
        </div>
    </section>
</main>
@endsection